### ISSUE TITLE
Email a summary to workshop participants

### ISSUE THREAD

**Issue by chatchavan** [transparentstats/guidelines#22]
Should we email workshop participants with a summary what we plan to do next? Especially decisions we made after the workshop might not be communicated through all participants. (They may not check the Slack group, especially if they are also using Slack for their work on another Slack group.)

Here are some points off the top of my head:

* Decision to focus on guideline first
   * What & how can they contribute to the guideline
* For people who are interested in other elements (newsletter, badges), what can they do next? (e.g., an online document for collecting ideas and pointers)

Timing of the email: 

* As soon as possible to signal that we are actively working on this, or 
* After we are done with the effect size guideline and has a style guide and process guide

Audience:

* Only the workshop participants, or
* People in transparent statistics mailing list

**Comment by mjskay** [comment]
Agreed. For timing I vote: after we have the different effect size exemplar versions but before we finalize them, because that gives us a concrete "ask" (i.e. we can ask for feedback on those versions). It is also soon, because we are finishing the different versions of that in 5 days (May 30).

For audience, I don't have a strong opinion. Workshop participants might be good for the first summary / ask, since they will have the context for what we're trying to do with the exemplars. Then we make a polished effect size doc and style guide based on feedback from that, then we write the summary out to the mailing list with possibly another "ask" (for people who want to contribute to the first set of guidelines).

**Comment by chatchavan** [comment]
Makes sense.

**Comment by dragice** [comment]
+1 for first sending effect size guidelines to workshop participants, either merged or unmerged (merged doesn't necessarily mean finalized, and may be easier to process / engage with?).

**Comment by mjskay** [comment]
I think unmerged but compiled (as Chat did) might be best. Gives a couple of different versions for people to look at, so can solicit comparisons between them.
