### ISSUE TITLE
Add author info to Chapter 2 "Effect Size"

### ISSUE THREAD

**Issue by dragice** [transparentstats/guidelines#65]
Can be modeled after Chapter 1, just have to make sure everyone's listed.

**Comment by dragice** [comment]
done, added a pull request.

**Comment by mjskay** [comment]
A few other people also contributed to the original effect size doc during the workshop (based on the Google doc history):

Amelia McNamara
Janne Lindqvist
Jake Wobbrock
Yea-Seul Kim

To each of @AmeliaMN @profjanne @wobbrock @yeaseulkim : would you like your names added as authors on the draft version of the Effect Size guideline? For context, since the workshop we have expanded the Effect Size topic somewhat and are shortly going to release a call for more contributions to the rest of the Transparent Statistics guidelines. You can see the current version of the whole guidelines here: https://transparentstats.github.io/guidelines/ and of the Effect Size chapter specifically here: https://transparentstats.github.io/guidelines/effectsize.html

This short-term ask is whether or not you would like your name added under "Contributed to the writing" in the second link above. If so, say "yes" and we'll add it. Thanks!

**Comment by wobbrock** [comment]
Yes, sure! Please add me as “Jacob O. Wobbrock.” Thanks!

Sent from my iPhone.

On Jan 5, 2018, at 1:32 PM, Matthew Kay <notifications@github.com<mailto:notifications@github.com>> wrote:


A few other people also contributed to the original effect size doc during the workshop (based on the Google doc history):

Amelia McNamara
Janne Lindqvist
Jake Wobbrock
Yea-Seul Kim

To each of @AmeliaMN<https://github.com/ameliamn> @profjanne<https://github.com/profjanne> @wobbrock<https://github.com/wobbrock> @yeaseulkim<https://github.com/yeaseulkim> : would you like your names added as authors on the draft version of the Effect Size guideline? For context, since the workshop we have expanded the Effect Size topic somewhat and are shortly going to release a call for more contributions to the rest of the Transparent Statistics guidelines. You can see the current version of the whole guidelines here: https://transparentstats.github.io/guidelines/ and of the Effect Size chapter specifically here: https://transparentstats.github.io/guidelines/effectsize.html

This short-term ask is whether or not you would like your name added under "Contributed to the writing" in the second link above. If so, say "yes" and we'll add it. Thanks!

**Comment by profjanne** [comment]
Yes. Thanks, please do include me. The current draft is looking good.

All the best,
Janne

**Comment by yeaseulkim** [comment]
Yes, please. Thank you!

Yea-Seul

Yea-Seul Kim
Ph. D. student, Information School, University of Washington
http://students.washington.edu/yeaseul1/

**Comment by AmeliaMN** [comment]
Sure, add me as well! Amelia McNamara.

**Comment by mjskay** [comment]
Thanks all! I'll update the author list.
